- package-lock.json
- package.json
- playwright.config.ts
- src/routes/[id]/+page.svelte
- src/routes/[id]/Article.svelte
- tests/session.test.ts
> Copy raw text from user message or completion

- README.md
- src/routes/+layout.svelte
- src/routes/[id]/+page.svelte
- src/routes/[id]/Article.svelte
- tests/session.test.ts
> feat: flip orientation of prompt field & completions

- .github/workflows/publish.yml
- Dockerfile
- README.md
- package-lock.json
- package.json
- svelte.config.js
> feat: Build & publish Docker image for Hollama

- playwright.config.ts
- src/lib/components/Button.svelte
- src/lib/ollama.ts
- src/routes/[id]/+page.svelte
- tests/session.test.ts
> feat: add ability to stop completions

- src/routes/+error.svelte
- create file `+error.svelete` in `src/routes` file path to handle 404 and 500 errors
> fix: add error page

- .github/workflows/publish.yml
- src/lib/components/Metadata.svelte
- src/lib/components/SectionListItem.svelte
- src/lib/sessions.ts
- src/routes/knowledge/[id]/+page.svelte
- src/routes/sessions/[id]/+page.svelte
- tests/docs.test.ts
- tests/knowledge.test.ts
- Fixes Github Action for publishing the docker image to the registry
- Adds `<Metadata>` component
- Changes the order of the metadata details
- Fixes #95
> fix: minor bug fixes

- src/routes/sessions/[id]/+page.svelte
- tests/session.test.ts
- All errors can now be retried
- Adds a hint to explain the behavior in #103
> feat: add retry button to error messages

- .github/workflows/publish.yml
- Dockerfile
- Updates `package.json` with the version output of `semantic-release`
- Builds release for Cloudflare Pages and deploys it
- Builds Docker image and publishes it to GH's registry
> fix: release version is displayed in the UI

- package-lock.json
- package.json
- src/lib/components/Button.svelte
- src/lib/components/ButtonSubmit.svelte
- src/lib/components/FieldTextEditor.svelte
- src/routes/sessions/[id]/Article.svelte
- Fixes minor styling glitches with text editor in dark mode.
- Fixes minor styling issues in sessions with syntax highlighting in dark mode.
- Fixes minor styling issues with primary buttons in dark mode.
- Fixes #46
> fix: improved styling in dark-mode

- src/lib/components/FieldSelect.svelte
> fix: field select styling issue in Safari

- src/lib/components/Field.svelte
> fix: long knowledge gets cutoff

- .github/workflows/release.yml
- electron-builder.yml
- electron/resources/mac/entitlements.mac.plist
- package-lock.json
- package.json
> fix: sign macOS releases & add new release for `arm64`

- package-lock.json
- tests/session.test.ts
> fix: update vulnerable npm packages

- src/lib/components/FieldSelect.svelte
- src/lib/components/Markdown.svelte
- src/routes/sessions/[id]/+page.svelte
- src/routes/sessions/[id]/Prompt.svelte
- tests/session.test.ts
Closes #210 
- Fixes styling for tables in markdown responses
- Fixes an issue where a prompt could be submitted without choosing a model first
- Fixes another issue where clearing a model and switching sessions made the **Run** button disabled
- Styling updates to model select field
> fix: various minor bug fixes & styling updates

- src/lib/components/Markdown.svelte
- src/routes/sessions/[id]/Prompt.svelte
> fix: disable font ligatures

- README.md
- package-lock.json
- package.json
- src/i18n/en/index.ts
- src/i18n/i18n-types.ts
- src/lib/chat/openai.ts
- src/lib/components/Markdown.svelte
- src/lib/sessions.ts
- src/routes/motd/motd.md
- src/routes/sessions/[id]/+page.svelte
- src/routes/sessions/[id]/Article.svelte
- src/routes/sessions/[id]/Messages.svelte
- tests/controls.test.ts
- tests/knowledge.test.ts
- tests/session-interaction.test.ts
- tests/utils.ts
DeepSeek R1 returns it's reasoning process wrapped in `<think></think>` tags.
We parse those while the completion is underway and move it's contents to a collapsible UI component.
> feat: add dedicated UI for reasoning model responses

- Dockerfile
- SELF_HOSTING.md
- vite.config.ts
> feat: allow requests from specified hosts

- src/i18n/en/index.ts
- src/i18n/i18n-types.ts
- src/lib/components/ButtonEdit.svelte
- src/lib/components/SectionListItem.svelte
- src/lib/sessions.ts
- src/routes/motd/motd.md
- tailwind.config.js
- tests/knowledge.test.ts
- tests/session-interaction.test.ts
- tests/session-management.test.ts
> feat: edit session titles manually

- src/routes/motd/motd.md
- src/routes/sessions/[id]/+page.svelte
- src/routes/sessions/[id]/reasoningProcessor.ts
- tests/session-interaction.test.ts
- tests/session-parsing.test.ts
- tests/session-reasoning.test.ts
- tests/utils.ts
> feat: add support for `<thought>` reasoning tags

- package-lock.json
- package.json
- src/lib/components/EmptyMessage.svelte
- src/lib/components/Fieldset.svelte
- src/lib/components/Markdown.svelte
- src/lib/components/Metadata.svelte
- src/lib/components/P.svelte
- src/lib/components/SectionList.svelte
- updates various npm packages
- updates a handful of components to use Svelte 5's runes syntax
> chore: update dependencies

- src/routes/motd/motd.md
- src/routes/sessions/[id]/+page.svelte
- src/routes/sessions/[id]/Prompt.svelte
- tests/session-interaction.test.ts
> feat: add ability to submit images without prompts
